updates

diff --git a/move-window b/move-window
--- a/move-window
+++ b/move-window
@@ -198,20 +198,30 @@
 # > wmctrl command (move): "true -i -r 0xe00008 -e 0,0,1056,-1,-1"
 #-
 
+# 2019-11-07
+# - so apparently _NET_WM_STATE_STAYS_ON_TOP, ATOM exists (qt/kde specific?)
+#   re: https://cep.xray.aps.anl.gov/software/qt4-x11-4.8.6-browser/d2/dfc/namespace_q_xcb_atom.html
+# - "function _get_net_wm_state_atom" added the following line:
+#  add: #   _NET_WM_STATE_STAYS_ON_TOP, ATOM (qt/kde specific?)
+# - "function _set_window_position" added the following lines:
+#  add: #   _NET_WM_STATE_STAYS_ON_TOP, ATOM (qt/kde specific?)
+#  add: ( *_NET_WM_STATE_STAYS_ON_TOP* )
+#  add:   _HUMAN_READABLE_WM_STATE_ATOM+=", stays on top"
+#  add: ;;&
 # 2019-11-06
 # - comment cleanup throughout the script
-# - "function _parse_parameters" removed the following lines:
-#  was: # - assign default value if unset
-#  was: # - ${parameter:=word}
-#  was: _OUTPUT_XPROP_ID=${_OUTPUT_XPROP_ID:=$(xprop -id $_OPTION_WINDOW_ID 2>&1)}
-# - "function _pass_fail_by_window_type" removed the following lines:
-#  was: _OUTPUT_XPROP_ID=$(xprop -id $_OPTION_WINDOW_ID 2>&1)
-#  was: # - "-n string" = true if the length of string is non-zero
-#  was: if [[ -n $_OUTPUT_XPROP_ID ]]
-#  was: then
-#  was: else
-#  was:   _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (does not exist) specified"
-#  was: fi
+# - "function _parse_parameters" deleted the following lines:
+#  del: # - assign default value if unset
+#  del: # - ${parameter:=word}
+#  del: _OUTPUT_XPROP_ID=${_OUTPUT_XPROP_ID:=$(xprop -id $_OPTION_WINDOW_ID 2>&1)}
+# - "function _pass_fail_by_window_type" deleted the following lines:
+#  del: _OUTPUT_XPROP_ID=$(xprop -id $_OPTION_WINDOW_ID 2>&1)
+#  del: # - "-n string" = true if the length of string is non-zero
+#  del: if [[ -n $_OUTPUT_XPROP_ID ]]
+#  del: then
+#  del: else
+#  del:   _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (does not exist) specified"
+#  del: fi
 # - "function _show_help" changed the following line:
 #  was: -id <Window ID>   Window ID (in hexadecimal format)
 #   is: -id <Window ID>   Window ID (in lowercase hexadecimal format)
@@ -236,17 +246,17 @@
 #   is: # - 3rd step: verify it by its type
 #   is: _pass_fail_by_window_type
 # - moved the following routine:
-#       # - this is absolutely required for the TigerVNC client
-#       # - this must be done after "function _coordinates_calculate" &
-#       #   "function _coordinates_validate", but before setting up _COMMAND
-#       #   in "function _set_window_position"
-#       if [[ $_COORDINATE_X != -1 ]] \
-#       && [[ $_COORDINATE_Y != -1 ]]
-#       then
-#         # - $((expression))
-#         _COORDINATE_X=$(( $_COORDINATE_X + $_KLUDGE_X ))
-#         _COORDINATE_Y=$(( $_COORDINATE_Y + $_KLUDGE_Y ))
-#       fi
+#  mov: # - this is absolutely required for the TigerVNC client
+#  mov: # - this must be done after "function _coordinates_calculate" &
+#  mov: #   "function _coordinates_validate", but before setting up _COMMAND
+#  mov: #   in "function _set_window_position"
+#  mov: if [[ $_COORDINATE_X != -1 ]] \
+#  mov: && [[ $_COORDINATE_Y != -1 ]]
+#  mov: then
+#  mov:   # - $((expression))
+#  mov:   _COORDINATE_X=$(( $_COORDINATE_X + $_KLUDGE_X ))
+#  mov:   _COORDINATE_Y=$(( $_COORDINATE_Y + $_KLUDGE_Y ))
+#  mov: fi
 # > "function _parse_parameters" from here
 # > "function _coordinates_kludge" to here
 # - "function _parse_parameters" changed the calling order of some functions:
@@ -3157,6 +3167,7 @@ function _get_net_wm_state_atom()
   #   _NET_WM_STATE_SHADED, ATOM
   #   _NET_WM_STATE_SKIP_PAGER, ATOM
   #   _NET_WM_STATE_SKIP_TASKBAR, ATOM
+  #   _NET_WM_STATE_STAYS_ON_TOP, ATOM (qt/kde specific?)
   #   _NET_WM_STATE_STICKY, ATOM
 
   _NET_WM_STATE_ATOM=$(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_STATE(ATOM) = /!d ; /\(.* = \|,\)/ s///g')
@@ -4385,14 +4396,14 @@ function _pass_fail_by_window_id()
   # functions:
   # _eko_iod
   # _pass_fail_by_window_type
+  # _show_error
 
   # variables:
-  # _NET_CLIENT_LIST_WINDOW
   # _OPTION_WINDOW_ID
   # _OUTPUT_XPROP_ID
 
   # binaries:
-  # (none)
+  # xprop
 
   # builtins:
   # (none)
@@ -4402,15 +4413,7 @@ function _pass_fail_by_window_id()
   #     parent: "function _parse_parameters"
   #      child: "function _pass_fail_by_window_type"
   #   precedes: "function "
-  #   succeeds: "function _get_net_client_list_window"
-
-  # NET:
-  # - _NET_CLIENT_LIST, WINDOW[]/32
-
-  # "_NET_CLIENT_LIST(WINDOW): window id # "
-  # "0xe00008, "
-  # etc, etc
-  # "0x36007a2"
+  #   succeeds: "function "
 
   # NOTE:
   # - "function _pass_fail_by_window_type" already does the heavy lifting in
@@ -4525,89 +4528,87 @@ function _pass_fail_by_window_type()
   # - the tests below are extremely verbose so future edits are simplified
   # - case in point: _NET_WM_WINDOW_TYPE_NORMAL
 
-#+ marker edit +#
+  # - "-n string" = true if the length of string is non-zero
+  if [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_CLIENT_LIST(WINDOW): window id # /!d') ]]
+  then
+    _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (root window) specified"
+  fi
+
+  if ! $_BOOLEAN_PERMISSIVE
+  then
+
     # - "-n string" = true if the length of string is non-zero
-    if [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_CLIENT_LIST(WINDOW): window id # /!d') ]]
+    if [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_COMBO.*/!d') ]]
     then
-      _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (root window) specified"
-    fi
-
-    if ! $_BOOLEAN_PERMISSIVE
-    then
-
-      # - "-n string" = true if the length of string is non-zero
-      if [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_COMBO.*/!d') ]]
-      then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (combo) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DESKTOP.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DESKTOP.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (desktop) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DIALOG.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DIALOG.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (dialog) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DND.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DND.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (dnd) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DOCK.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DOCK.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (dock) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DROPDOWN_MENU.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_DROPDOWN_MENU.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (dropdown menu) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_MENU.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_MENU.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (menu) specified"
 
-#      # - "-n string" = true if the length of string is non-zero
-#      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_NORMAL.*/!d') ]]
-#      then
+#    # - "-n string" = true if the length of string is non-zero
+#    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_NORMAL.*/!d') ]]
+#    then
 #      _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (normal) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_NOTIFICATION.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_NOTIFICATION.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (notification) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_POPUP_MENU.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_POPUP_MENU.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (popup menu) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_SPLASH.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_SPLASH.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (splash) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_TOOLBAR.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_TOOLBAR.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (toolbar) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_TOOLTIP.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_TOOLTIP.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (tooltip) specified"
 
-      # - "-n string" = true if the length of string is non-zero
-      elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_UTILITY.*/!d') ]]
-      then
+    # - "-n string" = true if the length of string is non-zero
+    elif [[ -n $(echo "$_OUTPUT_XPROP_ID" | sed --expression='/^_NET_WM_WINDOW_TYPE(ATOM) = .*_NET_WM_WINDOW_TYPE_UTILITY.*/!d') ]]
+    then
       _show_error "invalid Window ID \"$_OPTION_WINDOW_ID\" (utility) specified"
-      fi
+    fi
 
-    fi # $_BOOLEAN_PERMISSIVE
-#- marker edit -#
+  fi # $_BOOLEAN_PERMISSIVE
 
   _eko_iod "#- _pass_fail_by_window_type -#"
 }
@@ -4675,7 +4676,7 @@ function _set_window_position()
   #   them all here
 
   # NOTE:
-  # - pay close attention to the syntax used in the first case statement below
+  # - pay close attention to the syntax used in the case statements below
   # - instead of ";;", use ";;&" below. do not use ";&"
 
   if $_BOOLEAN_STDOUT
@@ -4697,6 +4698,7 @@ function _set_window_position()
     #   _NET_WM_STATE_SHADED, ATOM
     #   _NET_WM_STATE_SKIP_PAGER, ATOM
     #   _NET_WM_STATE_SKIP_TASKBAR, ATOM
+    #   _NET_WM_STATE_STAYS_ON_TOP, ATOM (qt/kde specific?)
     #   _NET_WM_STATE_STICKY, ATOM
 
     case $_NET_WM_STATE_ATOM in
@@ -4736,6 +4738,9 @@ function _set_window_position()
       ( *_NET_WM_STATE_SKIP_TASKBAR* )
         _HUMAN_READABLE_WM_STATE_ATOM+=", skip taskbar"
       ;;&
+      ( *_NET_WM_STATE_STAYS_ON_TOP* )
+        _HUMAN_READABLE_WM_STATE_ATOM+=", stays on top"
+      ;;&
       ( *_NET_WM_STATE_STICKY* )
         _HUMAN_READABLE_WM_STATE_ATOM+=", sticky"
       ;;&
@@ -4743,7 +4748,7 @@ function _set_window_position()
         # - "-z string" = true if the length of string is zero
         if [[ -z $_NET_WM_STATE_ATOM ]]
         then
-          _HUMAN_READABLE_WM_STATE_ATOM="undefined"
+          _HUMAN_READABLE_WM_STATE_ATOM=undefined
         fi
       ;;
     esac # $_NET_WM_STATE_ATOM
@@ -4753,6 +4758,9 @@ function _set_window_position()
     then
       _HUMAN_READABLE_WM_STATE_ATOM=${_HUMAN_READABLE_WM_STATE_ATOM:2}
     fi
+
+    # - be explicit for clarity
+    unset _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM
 
     # (sorted listing from the original source)
     #   _NET_WM_WINDOW_TYPE_COMBO, ATOM
@@ -4771,52 +4779,62 @@ function _set_window_position()
     #   _NET_WM_WINDOW_TYPE_UTILITY, ATOM
 
     case $_NET_WM_WINDOW_TYPE_ATOM in
-      ( _NET_WM_WINDOW_TYPE_COMBO )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=combo
-      ;;
-      ( _NET_WM_WINDOW_TYPE_DESKTOP )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=desktop
-      ;;
-      ( _NET_WM_WINDOW_TYPE_DIALOG )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=dialog
-      ;;
-      ( _NET_WM_WINDOW_TYPE_DND )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=dnd
-      ;;
-      ( _NET_WM_WINDOW_TYPE_DOCK )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=dock
-      ;;
-      ( _NET_WM_WINDOW_TYPE_DROPDOWN_MENU )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM="dropdown menu"
-      ;;
-      ( _NET_WM_WINDOW_TYPE_MENU )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=menu
-      ;;
-      ( _NET_WM_WINDOW_TYPE_NORMAL )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=normal
-      ;;
-      ( _NET_WM_WINDOW_TYPE_NOTIFICATION )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=notification
-      ;;
-      ( _NET_WM_WINDOW_TYPE_POPUP_MENU )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM="popup menu"
-      ;;
-      ( _NET_WM_WINDOW_TYPE_SPLASH )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=splash
-      ;;
-      ( _NET_WM_WINDOW_TYPE_TOOLBAR )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=toolbar
-      ;;
-      ( _NET_WM_WINDOW_TYPE_TOOLTIP )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=tooltip
-      ;;
-      ( _NET_WM_WINDOW_TYPE_UTILITY )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=utility
-      ;;
+      ( *_NET_WM_WINDOW_TYPE_COMBO* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", combo"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_DESKTOP* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", desktop"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_DIALOG* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", dialog"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_DND* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", dnd"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_DOCK* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", dock"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_DROPDOWN_MENU* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", dropdown menu"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_MENU* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", menu"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_NORMAL* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", normal"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_NOTIFICATION* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", notification"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_POPUP_MENU* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", popup menu"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_SPLASH* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", splash"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_TOOLBAR* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", toolbar"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_TOOLTIP* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", tooltip"
+      ;;&
+      ( *_NET_WM_WINDOW_TYPE_UTILITY* )
+        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM+=", utility"
+      ;;&
       ( * )
-        _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=undefined
+        # - "-z string" = true if the length of string is zero
+        if [[ -z $_NET_WM_WINDOW_TYPE_ATOM ]]
+        then
+          _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=undefined
+        fi
       ;;
     esac # $_NET_WM_WINDOW_TYPE_ATOM
+
+    # - tidy up
+    if [[ ${_HUMAN_READABLE_WM_WINDOW_TYPE_ATOM:0:2} == ", " ]]
+    then
+      _HUMAN_READABLE_WM_WINDOW_TYPE_ATOM=${_HUMAN_READABLE_WM_WINDOW_TYPE_ATOM:2}
+    fi
 
   fi # $_BOOLEAN_STDOUT
 
